### DISCUSSION TITLE
Questions about `sv2_ffi` crate

### DISCUSSION THREAD

**Discussion by plebhash** [stratum-mining/stratum#895] [General]
While planning our strategic roadmap, @Fi3 mentioned FFI needs to be updated.

Also, I'm working on the documentation effort described on https://github.com/stratum-mining/stratum/issues/845

This Github Discussion is meant to collect info (Q&A) for those tasks

**Comment by plebhash** [comment]
@Fi3 you mentioned this:
> sv2 ffi needs to be updated also we don't expose everything

can you elaborate?
which APIs are currently being exposed, but shouldn't?

**Reply by Fi3** [reply]
We currently expose:

```toml
[dependencies]
codec_sv2 = { path = "../../../protocols/v2/codec-sv2", version = "^1.0.0" }
const_sv2 = { path = "../../../protocols/v2/const-sv2", version = "^1.0.0" }
binary_sv2 = { path = "../../../protocols/v2/binary-sv2/binary-sv2", version = "^1.0.0" }
common_messages_sv2 = { path = "../../../protocols/v2/subprotocols/common-messages", version = "^1.0.0" }
template_distribution_sv2 = { path = "../../../protocols/v2/subprotocols/template-distribution", version = "^1.0.0" }
```

from https://github.com/stratum-mining/stratum/blob/cffbe5cf70d2aedbdbe0b6c9152140f0b505a3af/protocols/v2/sv2-ffi/Cargo.toml

This is the stricter subset of the SRI core libs to run a TP. That cause this crate was initially intended to be imported in bitcoin core so the requirement were: (1) less code possible to review (2) no external dependency. As you can see there is no noise functionality here, that because in the first draft of the Sv2 specification the TP wasn't supposed to support an encrypted connection.
