### ISSUE TITLE
Coverage workflow suggestions

### ISSUE THREAD

**Issue by lucasbalieiro** [stratum-mining/stratum#1766]
The `coverage-roles.yaml` workflow currently runs on **every pull request**, and consistently takes around **27 minutes** to complete. While it runs reliably (0% failure rate), it doesn’t appear to add much value during most PR reviews (IMO).

This adds unnecessary wait time to contributors and slows down CI feedback loops.

#### Overview of CI Workflows (Last 30 Days)

| **Workflow**             | **Failure Rate** | **Avg. Time** |
| ------------------------ | ---------------- | ------------- |
| `integration-tests.yaml` | 13%              | 42m 10s       |
| `coverage-roles.yaml`    | 0%               | 27m 8s        |
| `test.yaml`              | 13%              | 16m 28s       |

#### Coverage Workflows

These coverage workflows are stable, but I think they're not critical to PR validation. I see their main value is ensuring long-term coverage tracking — not gatekeeping PR merges like integration tests or linting.

| **Workflow**              | **Failure Rate** | **Avg. Time** |
| ------------------------- | ---------------- | ------------- |
| `coverage-roles.yaml`     | 0%               | 26m 57s       |
| `coverage-protocols.yaml` | 0%               | 7m 10s        |
| `coverage-utils.yaml`     | 0%               | 2m 22s        |

---

### Option 1: Convert `coverage-roles.yaml` to a Scheduled Workflow

We can convert this workflow (maybe all the coverage workflows) into a **daily cron job**, reducing CI load and review latency, while still keeping coverage metrics up to date.

```yaml
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:        # Allows manual trigger if needed
```
---

### Option 2: Keep on PRs, But Make It Smarter

If we want to retain PR-level coverage checks, here are two ways to optimize:

#### a. Add **Path Filters**

Run `coverage-roles.yaml` only if files in the `roles/` directory are changed. This reduces unnecessary executions.

```yaml
on:
  pull_request:
    branches:
      - main
    paths:
      - 'roles/**' # Only run if files in roles/ are modified
  workflow_dispatch:
```

#### b. (Unsure but could be a good idea) Split into **Parallel Jobs**

The job could be split into **parallelized sub-jobs** that run independently per role (if GitHub Actions limits allow this).

```yaml
jobs:
  coverage-job-1:
    runs-on: ubuntu-latest
    steps:
      # Coverage for subset of roles

  coverage-job-2:
    runs-on: ubuntu-latest
    steps:
      # Another subset

  coverage-job-3:
    runs-on: ubuntu-latest
    steps:
      # Final subset
```

Currently, the workflow runs as a single job and in for loop inside a bash script, which can be slow. Parallelizing could significantly reduce the total run time. (But this is just speculative)

---

## Recent Commit Patterns

Over the past 6 months, most development activity seems to be concentrated in the `protocols/` directory, not  individual `roles`.

| **# of Commits** | **Most Active Folders**   |
| ----------------- | ------------------------- |
| 707               | `protocols/v2`            |
| 189               | `roles/jd-client`         |
| 147               | `roles/tests-integration` |
| 133               | `roles/pool`              |
| 119               | `roles/translator`        |
| 93                | `roles/jd-server`         |
| 66                | `roles/roles-utils`       |
| 57                | `roles/mining-proxy`      |
| 55                | `roles/test-utils`        |

But when grouping `roles` and `protocols` in the past 6 months:

| **# of Commits** | **Most Active Folders**   |
| ----------------- | ------------------------- |
| 912               | `roles`                   |
| 734               | `protocols`               |

Also looking at which folders are commonly changed together:

| **# of Commits** | **Folders Changed Together**    |
| ---------------- | ------------------------------- |
| 39               | `protocols`, `roles`            |
| 15               | `.github`, `test`               |
| 12               | `roles`, `test`                 |
| 7                | `protocols`, `roles`, `test`    |
| 7                | `common`, `protocols`           |
| 4                | `roles`, `utils`                |
| 4                | `examples`, `roles`, `test`     |
| 4                | `benches`, `protocols`, `roles` |
| 3                | `.github`, `scripts`            |
| 3                | `common`, `protocols`, `roles`  |

Seeing this, the path filters solution could reduce unnecessary runs, but there’s a catch: when `roles/` *is* modified, it often appears alongside changes to other parts of the codebase (e.g., `test/`, `protocols/`, etc.). This defeats the purpose of filtering, as even collateral updates may end up triggering the coverage job. Which supports the idea of moving `coverage-roles.yaml` to a scheduled job that runs daily or weekly, instead of on every PR.

### Commands
```bash
git log --since="6 months ago" --name-only --pretty=format: | \
  grep -E '^(roles|protocols)/' | \
  cut -d/ -f1 | \
  sort | uniq -c | sort -nr

```

```bash
git log --since="6 months ago" --pretty=format:'---%H' --name-only \
| awk '
  /^---/ { if (folders) { print folders }; folders="" }
  /^[^---]/ && NF { split($0, a, "/"); if (folders !~ a[1]) folders = folders ? folders "," a[1] : a[1] }
' \
| grep ',' \
| sort \
| uniq -c \
| sort -nr \
| head
```
```bash
git log --since="6 months ago" --name-only --pretty=format: | \
  grep -E '^protocols/|^common/|^roles/|^utils/' | \
  cut -d/ -f1,2 | sort | uniq -c | sort -nr | head
```
