### ISSUE TITLE
Remove codecov/patch from GitHub Actions

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#206]
`codecov/patch` makes it looks like actions are failing when they are passing
Figure out how to remove it in the `.github/workflows/coverage.yaml`

[codecov/patch docs](https://docs.codecov.com/docs/commit-status#patch-status) say you should be able to turn it off with:
```
coverage:
  status:
    project: on
    patch: off
```
But it is unclear how this works in this project's `.github/workflows/coverage.yaml`.
