### ISSUE TITLE
MG Github Action is finicky

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#377]
The MG GitHub Action is finicky and fails frequently. PR #378 remove this action as it was blocking other PRs from being merged.

Here is the MG GitHub Action that should be fixed and restored:
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: message generator check

jobs:
  message_generator_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1

        with:
          profile: minimal
          toolchain: 1.57.0
          override: true
      - name: Run message generator tests
        run: sh ./message-generator-tests.sh
```
