### ISSUE TITLE
Braiins drops connection to translator

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#560]
On the latest main commit ffd21f5085eaf7435c54c5a226a09d44c440c07f.

My local config is set for a CPU miner, so I thought perhaps the pool hangs up because the hash rate I advertise is too low. But increasing `channel_nominal_hashrate` doesn't fix the issue.

```
RUST_BACKTRACE=1 cargo run -p translator_sv2 -- -c ~/.stratum/proxy-config.toml 

    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/translator_sv2 -c /home/stratum/.stratum/proxy-config.toml`
2023-05-08T11:34:47.804325Z  INFO translator_sv2: PC: ProxyConfig { upstream_address: "18.196.32.109", upstream_port: 3336, upstream_authority_pubkey: EncodedEd25519PublicKey { inner: PublicKey(CompressedEdwardsY: [118, 99, 112, 0, 151, 156, 28, 17, 175, 12, 48, 11, 205, 140, 127, 228, 134, 16, 252, 233, 185, 193, 30, 61, 174, 227, 90, 224, 176, 138, 116, 85]), EdwardsPoint{
	X: FieldElement51([2201803923854904, 2048790219505794, 1970562316326631, 1378635232623691, 2195959441710430]),
	Y: FieldElement51([1298072268202870, 458934462046755, 2234491558034995, 518001231191284, 1503344502637998]),
	Z: FieldElement51([1, 0, 0, 0, 0]),
	T: FieldElement51([1893592934976211, 796930100662777, 308776686920941, 1973432823513755, 2083308545938110])
}) }, downstream_address: "0.0.0.0", downstream_port: 63077, max_supported_version: 2, min_supported_version: 2, min_extranonce2_size: 16, jn_config: None, downstream_difficulty_config: DownstreamDifficultyConfig { min_individual_miner_hashrate: 300000000.0, miner_num_submits_before_update: 5, shares_per_minute: 2.0, submits_since_last_update: 0, timestamp_of_last_update: 0 }, upstream_difficulty_config: UpstreamDifficultyConfig { channel_diff_update_interval: 60, channel_nominal_hashrate: 300000000.0, timestamp_of_last_update: 0, should_aggregate: false }, test_only_share_withhold: false }
2023-05-08T11:34:47.813992Z  INFO translator_sv2::upstream_sv2::upstream: PROXY SERVER - ACCEPTING FROM UPSTREAM: 18.196.32.109:3336
2023-05-08T11:34:47.823113Z ERROR network_helpers::noise_connection_async_std: Shutting down noise stream reader! Os {
    code: 104,
    kind: ConnectionReset,
    message: "Connection reset by peer",
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/stratum/src/stratum/utils/network-helpers/src/noise_connection_async_std.rs:168:61
stack backtrace:
   0: rust_begin_unwind

...
```

Config:
```toml
# Braiins Pool Upstream Connection
upstream_authority_pubkey = "u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt"
upstream_address = "18.196.32.109"
upstream_port = 3336

# Local Mining Device Downstream Connection
downstream_address = "0.0.0.0"
downstream_port = 63077

# Version support
max_supported_version = 2
min_supported_version = 2

# Minimum extranonce2 size
min_extranonce2_size = 16
coinbase_reward_sat = 5_000_000_000

# Difficulty params
[downstream_difficulty_config]
# hashes/s of the weakest miner that will be connecting
min_individual_miner_hashrate=300_000_000
# interval in seconds to elapse before updating the hashrate of a downstream connection
miner_num_submits_before_update=5
# target number of shares per minute the miner should be sending
shares_per_minute = 2.0

[upstream_difficulty_config]
# interval in seconds to elapse before updating channel hashrate with the pool
channel_diff_update_interval = 60
# estimated accumulated hashrate of all downstream miners
channel_nominal_hashrate = 300_000_000
```
