### ISSUE TITLE
Job Declarator Server (JDS) should log that it's listening

### ISSUE THREAD

**Issue by Sjors** [stratum-mining/stratum#878]
This falls under the general category of needing more useful log and error messages.

I have the following JDS config:

```toml
# SRI Pool config
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

coinbase_outputs = [
   { output_script_type = "P2TR", output_script_value = "..." }
]

# SRI Pool JD config
listen_jd_address = "127.0.0.1:4264"

# RPC config for mempool
core_rpc_url =  "http://127.0.0.1"
core_rpc_port = 8342
core_rpc_user =  "jds"
core_rpc_pass =  "..."

[mempool_update_interval]
unit = "secs"
value = 10
```

The local Bitcoin Core node is configured to listen on RPC port 8342.

When I start the JDS (dev branch @ 60465ad2ac98478e04cb0eb0bc7cd66a141539a5) I see the following:

```
cargo run .. -- -c ~/.stratum/mainnet-jd-server.toml
...
    Finished dev [optimized + debuginfo] target(s) in 0.05s
     Running `/home/sjors/dev/stratum/roles/target/debug/jd_server .. -- -c /home/sjors/.stratum/mainnet-jd-server.toml`
2024-04-30T08:18:00.128835Z  INFO jd_server: Jds INITIALIZING with config: "/home/sjors/.stratum/mainnet-jd-server.toml"
2024-04-30T08:18:00.128870Z  INFO jd_server::lib::job_declarator: JD INITIALIZED
```

For some reason my JDC fails to connect to it, so it's useful for debugging to know if everything is OK with the JDS.

Currently it's tedious to find out.

It seems to be listening:

```
sudo lsof -i -P -n | grep LISTEN | grep 4264
jd_server 1877661           sjors   10u  IPv4 9837322      0t0  TCP 127.0.0.1:4264 (LISTEN
```

I can also see that it's successfully making a `getrawmempool` RPC call.

---

I suggest adding logging for at least:

1. That it's listening on a port
2. That it made a successful RPC connection (just the first one is enough)
